import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlProvider } from "next-intl";
import { useRouter } from "next/router";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { locale, messages } = useRouter();

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlProvider messages={messages} locale={locale}>
          {children}
        </NextIntlProvider>
      </body>
    </html>
  );
}
